public class ProvisioningRequest 
{
    @InvocableVariable
    public string ManifestId;
    @InvocableVariable
    public string Company;
    @InvocableVariable
    public string Country;
    @InvocableVariable
    public string FirstName;
    @InvocableVariable
    public string LastName;
    @InvocableVariable
    public string Notes;
    @InvocableVariable
    public string Edition;
    @InvocableVariable
    public string Language;
    @InvocableVariable
    public string Email;
    @InvocableVariable
    public string Subdomain;
    @InvocableVariable
    public integer TrialDays;
    @InvocableVariable
    public string Username;
    @InvocableVariable
    public string OrgId;
}